# Generated by Django 4.1.7 on 2023-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0005_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='img/placeholder.jpeg', upload_to='img/tests'),
        ),
    ]
