# Generated by Django 4.1.7 on 2023-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatwedo', '0006_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='img/placeholder.jpeg', upload_to='img/tests')),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('isMain', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Story',
            },
        ),
    ]
