# Generated by Django 4.1.7 on 2023-05-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Member',
            },
        ),
    ]
