# Generated by Django 4.1.7 on 2023-05-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.member'),
        ),
    ]
