# Generated by Django 4.1.7 on 2023-05-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_cordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='img/placeholder1.png', upload_to='img/project'),
        ),
    ]
