# Generated by Django 4.1.7 on 2023-05-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.member'),
        ),
    ]
