# Generated by Django 4.1.7 on 2023-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_cordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOverView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('btn_text', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ProjectOverView',
                'verbose_name_plural': 'ProjectOverView',
            },
        ),
    ]
