# Generated by Django 4.1.7 on 2023-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MovingText',
                'verbose_name_plural': 'MovingText',
            },
        ),
        migrations.CreateModel(
            name='MovingWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=500)),
                ('isLink', models.BooleanField()),
                ('linkAddress', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
