# Generated by Django 4.1.7 on 2023-04-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0002_movingword_delete_movingwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movingword',
            options={'verbose_name': 'MovingWord', 'verbose_name_plural': 'MovingWord'},
        ),
    ]
