# Generated by Django 4.1.7 on 2023-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0003_alter_movingword_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='img/slider')),
                ('btn', models.CharField(max_length=100)),
                ('btn_link', models.CharField(max_length=500)),
                ('color', models.CharField(choices=[('blue', 'blue'), ('brown', 'brown'), ('orange', 'orange'), ('purple', 'purple')], max_length=20)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
