# Generated by Django 4.1.7 on 2023-05-01 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0005_introduction_member_project_csoaimages_csoacards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='partners/img')),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csoa.member')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School',
            },
        ),
    ]
