# Generated by Django 4.1.7 on 2023-05-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_member'),
        ('csoa', '0007_impact_latestengagement_subscriber_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.member'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
