# Generated by Django 4.1.7 on 2023-05-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0008_alter_school_director_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
