# Generated by Django 4.1.7 on 2023-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0009_partners_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
