# Generated by Django 4.1.7 on 2023-05-02 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0010_introduction_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csoaimages',
            name='card',
        ),
        migrations.AddField(
            model_name='csoacards',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csoa.csoaimages'),
        ),
    ]
