# Generated by Django 4.1.7 on 2023-05-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0011_remove_csoaimages_card_csoacards_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impact',
            options={'verbose_name': 'Impact', 'verbose_name_plural': 'Impact'},
        ),
    ]
