# Generated by Django 4.1.7 on 2023-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0012_alter_impact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='percent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
