# Generated by Django 4.1.7 on 2023-05-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0014_header_latestengagement_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestengagement',
            name='header',
        ),
    ]
