# Generated by Django 4.1.7 on 2023-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csoa', '0015_remove_latestengagement_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestengagement',
            name='image',
            field=models.ImageField(default='img/placeholder1.png', upload_to='img/engagements'),
        ),
    ]
